---

- name: config hosts
  copy:
    src: hosts
    dest: /etc/hosts
    force: yes
    mode: '0644'

- name: config yum repo
  copy:
    src: CentOS-Base.repo
    dest: /etc/yum.repos.d/CentOS-Base.repo
    force: yes
    mode: '0644'

- name: install docker required packages
  yum:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present

- name: add docker repo
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: update yum
  shell: yum -y update

- name: install docker
  yum:
    name:
      - docker-ce-18.06.2.ce

- name: create docker dir
  file:
    path: /etc/docker
    state: directory
    mode: "0755"

- name: docker daemon json file
  copy:
    src: daemon.json
    dest: /etc/docker/daemon.json
    mode: '0644'

- name: docker proxy config dir
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: "0755"

- name: docker proxy config file
  copy:
    src: proxy.conf
    dest: /etc/systemd/system/docker.service.d/proxy.conf
    mode: '0644'

- name: systemd reload
  shell: systemctl daemon-reload

- name: systemd enable docker
  shell: systemctl enable docker

- name: systemd start docker
  shell: systemctl restart docker

- name: load br netfilter
  modprobe:
    name: br_netfilter
    state: present

- name: create k8s conf
  copy:
    src: k8s.conf
    dest: /etc/sysctl.d/k8s.conf
    mode: "0644"

- name: activate k8s conf
  shell: sysctl -p /etc/sysctl.d/k8s.conf

- name: add k8s yum repo
  copy: 
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
    mode: '0644'
