---

- name: pip install ss
  pip:
    name: shadowsocks

- name: yum install libsodium
  yum:
    name: libsodium
    state: present

- name: prepare ss dirs
  file:
    path: /etc/shadowsocks
    state: directory
    mode: "0755"

- name: create ss config file
  template:
    src: shadowsocks.json.j2
    dest: /etc/shadowsocks/shadowsocks.json
    mode: "0644"


- name: create ss systemd unit file
  copy:
    src: shadowsocks.service
    dest: /etc/systemd/system/shadowsocks.service
    mode: "0644"

- name: systemd enable ss
  systemd:
    name: shadowsocks
    enabled: yes
    masked: no

- name: systemd start ss
  systemd:
    name: shadowsocks
    state: started

- name: check ss status
  shell: curl --socks5 127.0.0.1:1080 http://httpbin.org/ip
  args:
    warn: no

- name: yum install privoxy
  yum:
    name: privoxy
    state: present

- name: config privoxy
  lineinfile:
    path: /etc/privoxy/config
    line: forward-socks5 / 127.0.0.1:1080 .

- name: systemd enable privoxy
  systemd:
    name: privoxy
    enabled: yes
    masked: no

- name: systemd start privoxy
  systemd:
    name: privoxy
    state: started

- name: add proxy
  lineinfile:
    path: /etc/profile
    line: "{{ item }}"
  with_items:
     - PROXY_HOST=127.0.0.1
     - export http_proxy=http://$PROXY_HOST:8118
     - export https_proxy=http://$PROXY_HOST:8118
     - export no_proxy=localhost,127.0.0.1,10.96.0.0/12,10.244.0.0/16,172.26.0.0/16,172.17.0.0/16

- name: activate proxy env
  shell: source {{ item }}
  with_items:
    - /etc/profile

- name: .bashrc proxy config
  lineinfile:
    path: /root/.bashrc
    line: "{{ item }}"
  with_items:
     - PROXY_HOST=127.0.0.1
     - export http_proxy=http://$PROXY_HOST:8118
     - export https_proxy=http://$PROXY_HOST:8118
     - export no_proxy=localhost,127.0.0.1,10.96.0.0/12,10.244.0.0/16,172.26.0.0/16,172.17.0.0/16







