---

- name: pip install ss
  pip:
    name: shadowsocks

- name: prepare ss dirs
  file:
    path: /etc/shadowsocks
    state: directory
    mode: "0755"

- name: create ss config file
  template:
    src: shadowsocks.json.j2
    dest: /etc/shadowsocks/shadowsocks.json
    mode: "0644"


- name: create ss systemd unit file
  template:
    src: shadowsocks.service.j2
    dest: /etc/systemd/system/shadowsocks.service
    mode: "0644"

- name: systemd enable ss
  systemd:
    name: shadowsocks
    enabled: yes
    masked: no

- name: systemd start ss
  systemd:
    name: shadowsocks
    state: started

- name: check ss status
  shell: curl --socks5 127.0.0.1:1080 http://httpbin.org/ip
  args:
    warn: no

- name: yum install privoxy
  yum:
    name: privoxy

- name: config privoxy
  lineinfile:
    path: /etc/privoxy/config
    line: forward-socks5 / 127.0.0.1:1080 .

- name: systemd enable privoxy
  systemd:
    name: privoxy
    enabled: yes
    masked: no

- name: systemd start privoxy
  systemd:
    name: privoxy
    state: started

- name: export proxy
  shell: "export http_proxy=http://127.0.0.1:8118; export https_proxy=http://127.0.0.1:8118"







